### PR TITLE
Two new pieces

### PR DESCRIPTION
**Pull request by MatthewVita**
Well, I just can't get Hugo working but I carefully did this by hand so it may be okay.

@robertdown and @bradymiller please spin this up on your end to see if anything is off 🙂.

It was like coding with blinders on haha

### CODE REVIEW

**Comment by robertdown** [comment]
@MatthewVita ping me about this on Wednesday evening

**Comment by bradymiller** [comment]
@MatthewVita and @robertdown ,
Here's a minor fix in the picture name for the imaging blog item:
https://github.com/openemr/blog/commit/eb3dafe11e7be11c5b7f4b89bfc1db889cf9287e

**Comment by MatthewVita** [comment]
@robertdown Ping :). Also, Brady helped me get Hugo running.

@bradymiller Okay, see the last 2 commits. Thanks.

**Comment by bradymiller** [comment]
@MatthewVita and @robertdown ,
I brought in the blog entry for the imaging. Note I had to do it in a weird way since missing the 3 blog entries from the repo. See here for details:
https://github.com/openemr/blog/pull/8

**Comment by bradymiller** [comment]
@MatthewVita , on the long term solution, it looks like @robertdown made the following image in chat:
image
Should we use this instead?

**Comment by bradymiller** [comment]
@MatthewVita and @robertdown ,
Just got the OpenEMR, A Great Long Term Choice blog entry up.

**Pull request closed without merging**
