### PR TITLE
Update openemr-availabile-on-aws.md

### PR DESCRIPTION
**Pull request by stephenwaite**
fixed typo

### CODE REVIEW

**Comment by bradymiller** [comment]
thanks @stephenwaite for the fix. I'll leave this to @robertdown to bring in since I am not sure if there is an automatic mechanism that brings this to aws to serve.

**Comment by bradymiller** [comment]
@stephenwaite and @robertdown ,
Should we be double spacing after sentences on blog entries? (I honestly have no idea :) )

**Comment by robertdown** [comment]
No. A thousand times no. Single spaces after a period. Forever. Period. End of discussion. Let's move on. This isn't the 19th century.

I'm mildly passionate about this

**Comment by sunsetsystems** [comment]
Spend your passion wisely, Robert. :) HTML does it your way at presentation time anyway.

**Comment by bradymiller** [comment]
:) http://www.slate.com/articles/technology/technology/2011/01/space_invaders.html

**Comment by bradymiller** [comment]
Looks good and thanks for the improvements! I just merged this in.

**Comment by bradymiller** [comment]
(will update website in near future with this)

**Comment by stephenwaite** [comment]
cool, thanks for the humorous link

**Comment by bradymiller** [comment]
website just updated :)
https://www.open-emr.org/blog/post/openemr-announces-initial-availability-of-openemr-cloud-on-aws/

**Pull request merged**
